a.out: homework.c ifrunnian gongyueshu showtime
	cc homework.c -g -Wall 

ifrunnian: ifrunnian.c
	cc ifrunnian.c -g -Wall -o ifrunnian

gongyueshu: gongyueshu.c
	cc gongyueshu.c -g -Wall -o gongyueshu

showtime: showtime.c
	cc showtime.c -g -Wall -o showtime

clean:
	rm a.out ifrunnian gongyueshu showtime
